---
# tasks file for prometheus

- name: check if prometheus exist
  stat:
    path: "{{ prometheus_bin }}"
  register: __check_prometheus_present

- name: create prometheus user
  user:
    name: "{{ prometheus_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create prometheus config dir
  file:
    path: "{{ prometheus_dir_conf }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: download and unzip prometheus if not exist
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no
  when: __check_prometheus_present.stat.exists == false

- name: move the binary to the final destination
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/"
    dest: "{{ prometheus_bin }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
    remote_src: yes
  when: __check_prometheus_present.stat.exists == false

- name: clean
  file:
    path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/
    state: absent

- name: install service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_prometheus

- name: service always started
  systemd:
    name: prometheus
    state: started
    enabled: yes


- name: prometheus configuration file
  template:
     src: prometheus.yml.j2
     dest: "{{ prometheus_dir_conf }}/prometheus.yml"
     mode: 0755
     owner: prometheus
     group: prometheus
  notify: reload_daemon_and_restart_prometheus 

- meta: flush_handlers